org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
jei_version=15.49.0.191
jei_version_range=[15.49.0.191,15.50)
mna_file_id=6847805
curios_file_id=5066845
geckolib_file_id=5460312
magichem_version=0.5.2-pre36

mod_id=putapinthat
mod_name=PutAPinInThat
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.vincenthuto.putapinthat
mod_authors=VincentHuto
mod_description=Pin JEI recipes to a persistent left-side HUD.
